name: "Hello Actions"

description: "Testing alpine image"

author: "adefemi171@github.com"



inputs:

  MY_NAME:

    description: "Testing out alpine image"

    required: true

    default: "World"



runs:

  using: "docker"

  image: "Dockerfile"



branding:

  icon: "mic"

  color: "purple"
